name: MMDT Simple ETL pipeline
on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 21 12 4 *" ## Trigger on April 12 - 9PM (timezone?)
  workflow_dispatch: ## manual trigger
jobs:
  simple-etl:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo content
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "pip"
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Test env vars for python
        run: python -c "import os; print(os.getenv("WEATHER_KEY"))"
        env:
          WEATHER_KEY: ${{ secrets.WEATHER_KEY }}
      - name: Run data pipeline
        run: python week9_demo/etl_demo.py
        env:
          WEATHER_KEY: ${{ secrets.WEATHER_KEY }}
